/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/hr/analytics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Hr Analytics */
    get: operations["hr_analytics_api_hr_analytics_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/examples/{filename}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Example File */
    get: operations["example_file_api_public_examples__filename__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public Config */
    get: operations["public_config_api_public_config_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Public Session */
    post: operations["public_session_api_public_session_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_api_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Version */
    get: operations["version_api_version_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign In */
    post: operations["sign_in_api_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign Out */
    post: operations["sign_out_api_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/catalog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catalog */
    get: operations["catalog_api_catalog_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/employees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Employees */
    get: operations["employees_api_employees_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/employees/{employee_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Employee */
    get: operations["employee_api_employees__employee_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/employees/{employee_id}/goal": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Goal */
    patch: operations["goal_api_employees__employee_id__goal_patch"];
    trace?: never;
  };
  "/api/employees/{employee_id}/recommendations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Recommendations */
    post: operations["recommendations_api_employees__employee_id__recommendations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/employees/{employee_id}/recommendations/latest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Latest */
    get: operations["latest_api_employees__employee_id__recommendations_latest_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/employees/{employee_id}/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview */
    post: operations["preview_api_employees__employee_id__preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/employees/{employee_id}/completions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Completions */
    post: operations["completions_api_employees__employee_id__completions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/hr/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Summary */
    get: operations["summary_api_hr_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/hr/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import Data */
    post: operations["import_data_api_hr_import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AICapability */
    AICapability: {
      /**
       * Status
       * @enum {string}
       */
      status: "not_configured" | "configured";
      /**
       * Engine
       * @enum {string}
       */
      engine: "none" | "oleg";
    };
    /** ActivityRecord */
    ActivityRecord: {
      /** Record Id */
      record_id: string;
      /** Event Id */
      event_id: string;
      /**
       * Status
       * @enum {string}
       */
      status:
        | "completed"
        | "in_progress"
        | "dropped"
        | "no_show"
        | "declined"
        | "overdue";
      /**
       * Activity Date
       * Format: date
       */
      activity_date: string;
      /**
       * Date Source
       * @enum {string}
       */
      date_source: "historical_proxy" | "completed_at";
      /** Completed At */
      completed_at?: string | null;
      /**
       * Mode
       * @default import
       * @enum {string}
       */
      mode: "import" | "completion" | "demo_simulation";
      /** Effects */
      effects?: components["schemas"]["SkillEffect"][];
    };
    /** BatchImportRequest */
    BatchImportRequest: {
      /**
       * Dry Run
       * @default true
       */
      dry_run: boolean;
      /** Files */
      files: components["schemas"]["SourceFile"][];
      /** Preview Token */
      preview_token?: string | null;
    };
    /** Capabilities */
    Capabilities: {
      ai: components["schemas"]["AICapability"];
      dataset: components["schemas"]["DatasetCapability"];
    };
    /** CatalogEvent */
    CatalogEvent: {
      /** Event Id */
      event_id: string;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /**
       * Type
       * @enum {string}
       */
      type:
        | "compliance"
        | "onboarding"
        | "course"
        | "workshop"
        | "mentoring"
        | "certification"
        | "meetup";
      /**
       * Format
       * @enum {string}
       */
      format: "online" | "offline" | "self_paced";
      /** Duration Hours */
      duration_hours: number;
      /** Mandatory */
      mandatory: boolean;
      /** Target Roles */
      target_roles: string[];
      /** Target Grades */
      target_grades: ("Junior" | "Middle" | "Senior" | "Lead")[];
      /** Develops Skills */
      develops_skills: components["schemas"]["CatalogSkillGain"][];
      /** Prerequisites */
      prerequisites: {
        [key: string]: number;
      };
      /** Upcoming Sessions */
      upcoming_sessions: string[];
    };
    /** CatalogResponse */
    CatalogResponse: {
      /** Data Version */
      data_version: string;
      /** Proficiency Scale */
      proficiency_scale: {
        [key: string]: string;
      };
      /** Skills */
      skills: components["schemas"]["CatalogSkill"][];
      /** Role Profiles */
      role_profiles: components["schemas"]["CatalogRole"][];
      /** Events */
      events?: components["schemas"]["CatalogEvent"][];
    };
    /** CatalogRole */
    CatalogRole: {
      /** Role */
      role: string;
      /**
       * Grade
       * @enum {string}
       */
      grade: "Junior" | "Middle" | "Senior" | "Lead";
      /** Required Skills */
      required_skills: {
        [key: string]: number;
      };
      /** Critical Skills */
      critical_skills: string[];
    };
    /** CatalogSkill */
    CatalogSkill: {
      /** Skill Id */
      skill_id: string;
      /** Name */
      name: string;
      /**
       * Type
       * @enum {string}
       */
      type: "hard" | "soft";
      /** Category */
      category: string;
      /** Description */
      description: string;
    };
    /** CatalogSkillGain */
    CatalogSkillGain: {
      /** Skill Id */
      skill_id: string;
      /** Gain */
      gain: number;
      /** Max Level */
      max_level: number;
    };
    /** CompletionRecord */
    CompletionRecord: {
      /** Completion Id */
      completion_id: string;
      /** Event Id */
      event_id: string;
      /**
       * Mode
       * @enum {string}
       */
      mode: "completion" | "demo_simulation";
      /**
       * Completed At
       * Format: date-time
       */
      completed_at: string;
      /** Effects */
      effects: components["schemas"]["SkillEffect"][];
    };
    /** CompletionRequest */
    CompletionRequest: {
      /** Expected State Version */
      expected_state_version: number;
      /** Event Id */
      event_id: string;
      /**
       * Mode
       * @enum {string}
       */
      mode: "completion" | "demo_simulation";
      /** Record Id */
      record_id?: string | null;
    };
    /** CompletionResponse */
    CompletionResponse: {
      /** State Version */
      state_version: number;
      completion: components["schemas"]["CompletionRecord"];
    };
    /** DatasetCapability */
    DatasetCapability: {
      /**
       * Status
       * @enum {string}
       */
      status: "not_loaded" | "loaded";
      /** Version */
      version?: string | null;
    };
    /** EmployeeDetailResponse */
    EmployeeDetailResponse: {
      /** Data Version */
      data_version: string;
      /** State Version */
      state_version: number;
      profile: components["schemas"]["EmployeeProfile"];
      goal: components["schemas"]["Goal"] | null;
      /** Current Skills */
      current_skills: components["schemas"]["SkillLevel"][];
      /** Gaps */
      gaps: components["schemas"]["SkillGap"][];
      /** History */
      history: components["schemas"]["ActivityRecord"][];
      /**
       * Scenario Date
       * Format: date
       * @default 2026-10-01
       */
      scenario_date: string;
      /**
       * Target Status
       * @default explicit
       * @enum {string}
       */
      target_status: "explicit" | "next_grade" | "no_target";
      progress?: components["schemas"]["Progress"] | null;
    };
    /** EmployeeListResponse */
    EmployeeListResponse: {
      /** Items */
      items: components["schemas"]["EmployeeProfile"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** EmployeeProfile */
    EmployeeProfile: {
      /** Employee Id */
      employee_id: string;
      /** Full Name */
      full_name: string;
      /** Department */
      department: string;
      /** Role */
      role: string;
      /**
       * Grade
       * @enum {string}
       */
      grade: "Junior" | "Middle" | "Senior" | "Lead";
    };
    /** ErrorResponse */
    ErrorResponse: {
      /** Code */
      code: string;
      /** Message */
      message: string;
      /** Request Id */
      request_id: string;
      /** Details */
      details?: {
        [key: string]: components["schemas"]["JsonValue"];
      };
    };
    /** Explanation */
    Explanation: {
      /** Text */
      text: string;
      /** Evidence Ids */
      evidence_ids: string[];
    };
    /** Goal */
    Goal: {
      /** Target Role */
      target_role: string;
      /**
       * Target Grade
       * @enum {string}
       */
      target_grade: "Junior" | "Middle" | "Senior" | "Lead";
    };
    /** GoalUpdateRequest */
    GoalUpdateRequest: {
      /** Expected State Version */
      expected_state_version: number;
      goal: components["schemas"]["Goal"];
    };
    /**
     * HRAnalyticsResponse
     * @description A deterministic, HR-only snapshot; observations are not a motivation score.
     */
    HRAnalyticsResponse: {
      /** Data Version */
      data_version: string;
      /** State Version */
      state_version: number;
      /**
       * Scenario Date
       * Format: date
       */
      scenario_date: string;
      /**
       * Period Start
       * Format: date
       */
      period_start: string;
      /**
       * Period End
       * Format: date
       */
      period_end: string;
      /** Window Days */
      window_days: number;
      /** Employee Count */
      employee_count: number;
      /** Employees With Goal */
      employees_with_goal: number;
      /** Employees With History */
      employees_with_history: number;
      /** Employees With Completion In Period */
      employees_with_completion_in_period: number;
      /** History Records In Period */
      history_records_in_period: number;
      /** Historical Proxy Records In Period */
      historical_proxy_records_in_period: number;
      /** Excluded Simulations */
      excluded_simulations: number;
      /** Skill Gaps */
      skill_gaps: components["schemas"]["HRSkillGap"][];
      /** Attention */
      attention: components["schemas"]["HRAttentionEmployee"][];
      /** Participation */
      participation: components["schemas"]["HRParticipation"][];
      /** Notes */
      notes: string[];
    };
    /** HRAttentionEmployee */
    HRAttentionEmployee: {
      profile: components["schemas"]["EmployeeProfile"];
      /** Reasons */
      reasons: components["schemas"]["HRAttentionReason"][];
      /** Last Completed Date */
      last_completed_date: string | null;
      /** History Records In Period */
      history_records_in_period: number;
      /** Completed In Period */
      completed_in_period: number;
      /** No Show In Period */
      no_show_in_period: number;
      /** Eligible Event Count */
      eligible_event_count: number;
      /** Progress Percent */
      progress_percent: number | null;
    };
    /** HRAttentionReason */
    HRAttentionReason: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | "no_history"
        | "no_recent_completion"
        | "repeated_no_show"
        | "no_candidates"
        | "no_target";
      /** Message */
      message: string;
    };
    /** HRParticipation */
    HRParticipation: {
      /** Event Id */
      event_id: string;
      /** Title */
      title: string;
      /** Type */
      type: string;
      /** Format */
      format: string;
      /** Mandatory */
      mandatory: boolean;
      /** Record Count */
      record_count: number;
      /** Participant Count */
      participant_count: number;
      /** Completed */
      completed: number;
      /** In Progress */
      in_progress: number;
      /** Dropped */
      dropped: number;
      /** No Show */
      no_show: number;
      /** Declined */
      declined: number;
      /** Overdue */
      overdue: number;
    };
    /** HRSkillGap */
    HRSkillGap: {
      /** Skill Id */
      skill_id: string;
      /** Skill Name */
      skill_name: string;
      /** Employees Requiring */
      employees_requiring: number;
      /** Employees With Gap */
      employees_with_gap: number;
      /** Gap Percent */
      gap_percent: number;
      /** Average Gap */
      average_gap: number;
      /** Critical Gap Count */
      critical_gap_count: number;
    };
    /** HRSummaryResponse */
    HRSummaryResponse: {
      /** Data Version */
      data_version: string;
      /** Employee Count */
      employee_count: number;
      /** Employees With Goal */
      employees_with_goal: number;
      /** Completion Count */
      completion_count: number;
      /** Demo Simulation Count */
      demo_simulation_count: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok";
      capabilities: components["schemas"]["Capabilities"];
    };
    /** ImportRequest */
    ImportRequest: {
      /**
       * Source Filename
       * @enum {string}
       */
      source_filename:
        | "skills.json"
        | "employees.json"
        | "events.json"
        | "activity_history.csv";
      /**
       * Source Format
       * @enum {string}
       */
      source_format: "json" | "csv";
      /** Content */
      content: string;
      /**
       * Dry Run
       * @default true
       */
      dry_run: boolean;
      /** Preview Token */
      preview_token?: string | null;
    };
    /** ImportResponse */
    ImportResponse: {
      /** Dry Run */
      dry_run: boolean;
      /**
       * Status
       * @enum {string}
       */
      status: "validated" | "imported";
      /** Data Version */
      data_version: string | null;
      /** Imported Records */
      imported_records: number;
      /** Warnings */
      warnings?: string[];
      /** Preview Token */
      preview_token?: string | null;
      /**
       * Revision
       * @default 0
       */
      revision: number;
      /** Counts */
      counts?: {
        [key: string]: number;
      };
    };
    JsonValue: unknown;
    /** LoginRequest */
    LoginRequest: {
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
    };
    /** LogoutResponse */
    LogoutResponse: {
      /**
       * Status
       * @default logged_out
       * @constant
       */
      status: "logged_out";
    };
    /** PreviewRequest */
    PreviewRequest: {
      /** Expected State Version */
      expected_state_version: number;
      /**
       * Scenario Date
       * Format: date
       */
      scenario_date: string;
      /** Event Ids */
      event_ids: string[];
    };
    /** PreviewResponse */
    PreviewResponse: {
      /** Data Version */
      data_version: string;
      /** State Version */
      state_version: number;
      /**
       * Scenario Date
       * Format: date
       */
      scenario_date: string;
      /**
       * Persisted
       * @default false
       * @constant
       */
      persisted: false;
      /** Effects */
      effects: components["schemas"]["SkillEffect"][];
      /** Projected Skills */
      projected_skills: components["schemas"]["SkillLevel"][];
      /** Projected Gaps */
      projected_gaps: components["schemas"]["SkillGap"][];
    };
    /** Progress */
    Progress: {
      /** Percent */
      percent: number;
      /** Met Skills */
      met_skills: number;
      /** Total Skills */
      total_skills: number;
      /** Critical Met */
      critical_met: number;
      /** Critical Total */
      critical_total: number;
    };
    /** PublicDemoConfig */
    PublicDemoConfig: {
      /** Enabled */
      enabled: boolean;
      /** Session Ttl Seconds */
      session_ttl_seconds: number;
      /** Ai Enabled */
      ai_enabled: boolean;
    };
    /** PublicSessionRequest */
    PublicSessionRequest: {
      /**
       * Role
       * @enum {string}
       */
      role: "employee" | "hr";
    };
    /** ReadinessResponse */
    ReadinessResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: "ready" | "not_ready";
      /**
       * Database
       * @enum {string}
       */
      database: "ready" | "unavailable" | "migration_required";
      capabilities: components["schemas"]["Capabilities"];
    };
    /** RecommendationRequest */
    RecommendationRequest: {
      /**
       * Scenario Date
       * Format: date
       */
      scenario_date: string;
      /**
       * Limit
       * @default 3
       */
      limit: number;
    };
    /** RecommendationResponse */
    RecommendationResponse: {
      /** Data Version */
      data_version: string;
      /** State Version */
      state_version: number;
      /**
       * Scenario Date
       * Format: date
       */
      scenario_date: string;
      /**
       * Status
       * @enum {string}
       */
      status:
        "ok" | "no_candidates" | "no_target" | "not_configured" | "unavailable";
      /**
       * Engine
       * @enum {string}
       */
      engine: "none" | "oleg";
      /** Recommendations */
      recommendations: components["schemas"]["RecommendedEvent"][];
      /** Recommendation Id */
      recommendation_id?: string | null;
      /**
       * Stale
       * @default false
       */
      stale: boolean;
    };
    /** RecommendedEvent */
    RecommendedEvent: {
      /** Event Id */
      event_id: string;
      /** Title */
      title: string;
      /** Effects */
      effects: components["schemas"]["SkillEffect"][];
      explanation: components["schemas"]["Explanation"];
    };
    /** SessionResponse */
    SessionResponse: {
      user: components["schemas"]["UserIdentity"];
      /** Csrf Token */
      csrf_token: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
    };
    /** SkillEffect */
    SkillEffect: {
      /** Skill Id */
      skill_id: string;
      /** Before */
      before: number;
      /** After */
      after: number;
      /** Delta */
      delta: number;
    };
    /** SkillGap */
    SkillGap: {
      /** Skill Id */
      skill_id: string;
      /** Current Level */
      current_level: number;
      /** Target Level */
      target_level: number;
      /** Gap */
      gap: number;
    };
    /** SkillLevel */
    SkillLevel: {
      /** Skill Id */
      skill_id: string;
      /** Level */
      level: number;
    };
    /**
     * SourceFile
     * @description Transport for an original source file; its content is validated by the importer.
     */
    SourceFile: {
      /**
       * Source Filename
       * @enum {string}
       */
      source_filename:
        | "skills.json"
        | "employees.json"
        | "events.json"
        | "activity_history.csv";
      /**
       * Source Format
       * @enum {string}
       */
      source_format: "json" | "csv";
      /** Content */
      content: string;
    };
    /** UserIdentity */
    UserIdentity: {
      /** Id */
      id: string;
      /** Username */
      username: string;
      /**
       * Role
       * @enum {string}
       */
      role: "employee" | "hr";
      /** Employee Id */
      employee_id: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VersionResponse */
    VersionResponse: {
      /**
       * Api Version
       * @default 1.0.0
       * @constant
       */
      api_version: "1.0.0";
      /** Commit Sha */
      commit_sha: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  hr_analytics_api_hr_analytics_get: {
    parameters: {
      query?: {
        window_days?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HRAnalyticsResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  example_file_api_public_examples__filename__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        filename: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  public_config_api_public_config_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicDemoConfig"];
        };
      };
    };
  };
  public_session_api_public_session_post: {
    parameters: {
      query?: never;
      header: {
        /** @description Exact allowlisted origin; browsers send this automatically. */
        Origin: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PublicSessionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  ready_api_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  version_api_version_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionResponse"];
        };
      };
    };
  };
  sign_in_api_auth_login_post: {
    parameters: {
      query?: never;
      header: {
        /** @description Exact allowlisted origin; browsers send this automatically. */
        Origin: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  sign_out_api_auth_logout_post: {
    parameters: {
      query?: never;
      header: {
        /** @description Exact allowlisted origin; browsers send this automatically. */
        Origin: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogoutResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  me_api_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserIdentity"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  catalog_api_catalog_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  employees_api_employees_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeListResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  employee_api_employees__employee_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeDetailResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  goal_api_employees__employee_id__goal_patch: {
    parameters: {
      query?: never;
      header: {
        /** @description Exact allowlisted origin; browsers send this automatically. */
        Origin: string;
      };
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GoalUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeDetailResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  recommendations_api_employees__employee_id__recommendations_post: {
    parameters: {
      query?: never;
      header: {
        /** @description Exact allowlisted origin; browsers send this automatically. */
        Origin: string;
      };
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecommendationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecommendationResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  latest_api_employees__employee_id__recommendations_latest_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecommendationResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  preview_api_employees__employee_id__preview_post: {
    parameters: {
      query?: never;
      header: {
        /** @description Exact allowlisted origin; browsers send this automatically. */
        Origin: string;
      };
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PreviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PreviewResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  completions_api_employees__employee_id__completions_post: {
    parameters: {
      query?: never;
      header: {
        /** @description Exact allowlisted origin; browsers send this automatically. */
        Origin: string;
        /** @description Reuse with the identical body after a lost response; checked after authorization and before revision. */
        "Idempotency-Key": string;
      };
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompletionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompletionResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  summary_api_hr_summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HRSummaryResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  import_data_api_hr_import_post: {
    parameters: {
      query?: never;
      header: {
        /** @description Exact allowlisted origin; browsers send this automatically. */
        Origin: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json":
          | components["schemas"]["ImportRequest"]
          | components["schemas"]["BatchImportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
